spring:
  profiles:
    active: dev

server:
  port: 8080

mybatis:
  typeAliasesPackage: com.example.demo.vo
  mapperLocations: classpath:mapper/*.xml

---

spring:
  datasource:
    my:
      url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      isPrimary: true

logging:
  level:
    com.example.demo.mapper: debug

---

jobs:
  schedule: 0/5 * * * * ?